# Dùng node bản nhẹ nhất
FROM node:18-alpine

# Set thư mục làm việc trong container
WORKDIR /app

# Copy 2 file package vào trước để cài thư viện
COPY package.json package-lock.json* ./

# Cài đặt thư viện
RUN npm install

# Copy toàn bộ code FE vào
COPY . .

# Mở cổng 5173 (Cổng mặc định của Vite)
EXPOSE 5173

# Lệnh khởi động FE (Kèm --host để Docker map port ra ngoài localhost được)
CMD ["npm", "run", "dev", "--", "--host"]